version: '3.8'

services:
  trader_dashboard:
    build: .
    container_name: trader_dashboard
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    dns:
      - 8.8.8.8
      - 1.1.1.1

  redis:
    image: redis:6-alpine
    container_name: trading_redis
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
